-- RedefineTables
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_PIZZA_INGREDIENTS" (
    "PizzaId" INTEGER NOT NULL,
    "IngredientId" INTEGER NOT NULL,

    PRIMARY KEY ("PizzaId", "IngredientId"),
    CONSTRAINT "PIZZA_INGREDIENTS_IngredientId_fkey" FOREIGN KEY ("IngredientId") REFERENCES "INGREDIENTS" ("Id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "PIZZA_INGREDIENTS_PizzaId_fkey" FOREIGN KEY ("PizzaId") REFERENCES "PIZZAS" ("Id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_PIZZA_INGREDIENTS" ("IngredientId", "PizzaId") SELECT "IngredientId", "PizzaId" FROM "PIZZA_INGREDIENTS";
DROP TABLE "PIZZA_INGREDIENTS";
ALTER TABLE "new_PIZZA_INGREDIENTS" RENAME TO "PIZZA_INGREDIENTS";
PRAGMA foreign_key_check;
PRAGMA foreign_keys=ON;
