-- CreateTable
CREATE TABLE "PIZZAS" (
    "Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT NOT NULL,
    "CreatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "PIZZA_INGREDIENTS" (
    "PizzaId" INTEGER NOT NULL,
    "IngredientId" INTEGER NOT NULL,

    PRIMARY KEY ("PizzaId", "IngredientId"),
    CONSTRAINT "PIZZA_INGREDIENTS_IngredientId_fkey" FOREIGN KEY ("IngredientId") REFERENCES "INGREDIENTS" ("Id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "PIZZA_INGREDIENTS_PizzaId_fkey" FOREIGN KEY ("PizzaId") REFERENCES "PIZZAS" ("Id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "PIZZAS_Name_key" ON "PIZZAS"("Name");
